import { Pokemon, Type } from "../models/associations.js";

const pokemonTypes = [
  { name: "Bulbizarre", types: ["Plante", "Poison"] },
  { name: "Herbizarre", types: ["Plante", "Poison"] },
  { name: "Florizarre", types: ["Plante", "Poison"] },
  { name: "Salamèche", types: ["Feu"] },
  { name: "Reptincel", types: ["Feu"] },
  { name: "Dracaufeu", types: ["Feu", "Vol"] },
  { name: "Carapuce", types: ["Eau"] },
  { name: "Carabaffe", types: ["Eau"] },
  { name: "Tortank", types: ["Eau"] },
  { name: "Chenipan", types: ["Insecte"] },
  { name: "Chrysacier", types: ["Insecte"] },
  { name: "Papilusion", types: ["Insecte", "Vol"] },
  { name: "Aspicot", types: ["Insecte", "Poison"] },
  { name: "Coconfort", types: ["Insecte", "Poison"] },
  { name: "Dardargnan", types: ["Insecte", "Poison"] },
  { name: "Roucool", types: ["Normal", "Vol"] },
  { name: "Roucoups", types: ["Normal", "Vol"] },
  { name: "Roucarnage", types: ["Normal", "Vol"] },
  { name: "Rattata", types: ["Normal"] },
  { name: "Rattatac", types: ["Normal"] },
  { name: "Piafabec", types: ["Normal", "Vol"] },
  { name: "Rapasdepic", types: ["Normal", "Vol"] },
  { name: "Abo", types: ["Poison"] },
  { name: "Arbok", types: ["Poison"] },
  { name: "Pikachu", types: ["Électrik"] },
  { name: "Raichu", types: ["Électrik"] },
  { name: "Sabelette", types: ["Sol"] },
  { name: "Sablaireau", types: ["Sol"] },
  { name: "Nidoran♀", types: ["Poison"] },
  { name: "Nidorina", types: ["Poison"] },
  { name: "Nidoqueen", types: ["Poison", "Sol"] },
  { name: "Nidoran♂", types: ["Poison"] },
  { name: "Nidorino", types: ["Poison"] },
  { name: "Nidoking", types: ["Poison", "Sol"] },
  { name: "Mélofée", types: ["Fée"] },
  { name: "Mélodelfe", types: ["Fée"] },
  { name: "Goupix", types: ["Feu"] },
  { name: "Feunard", types: ["Feu"] },
  { name: "Rondoudou", types: ["Normal", "Fée"] },
  { name: "Grodoudou", types: ["Normal", "Fée"] },
  { name: "Nosferapti", types: ["Poison", "Vol"] },
  { name: "Nosferalto", types: ["Poison", "Vol"] },
  { name: "Mystherbe", types: ["Plante", "Poison"] },
  { name: "Ortide", types: ["Plante", "Poison"] },
  { name: "Rafflesia", types: ["Plante", "Poison"] },
  { name: "Paras", types: ["Insecte", "Plante"] },
  { name: "Parasect", types: ["Insecte", "Plante"] },
  { name: "Mimitoss", types: ["Insecte", "Poison"] },
  { name: "Aéromite", types: ["Insecte", "Poison"] },
  { name: "Taupiqueur", types: ["Sol"] },
  { name: "Triopikeur", types: ["Sol"] },
  { name: "Miaouss", types: ["Normal"] },
  { name: "Persian", types: ["Normal"] },
  { name: "Psykokwak", types: ["Eau"] },
  { name: "Akwakwak", types: ["Eau"] },
  { name: "Férosinge", types: ["Combat"] },
  { name: "Colossinge", types: ["Combat"] },
  { name: "Caninos", types: ["Feu"] },
  { name: "Arcanin", types: ["Feu"] },
  { name: "Ptitard", types: ["Eau"] },
  { name: "Têtarte", types: ["Eau"] },
  { name: "Tartard", types: ["Eau", "Combat"] },
  { name: "Abra", types: ["Psy"] },
  { name: "Kadabra", types: ["Psy"] },
  { name: "Alakazam", types: ["Psy"] },
  { name: "Machoc", types: ["Combat"] },
  { name: "Machopeur", types: ["Combat"] },
  { name: "Mackogneur", types: ["Combat"] },
  { name: "Chétiflor", types: ["Plante", "Poison"] },
  { name: "Boustiflor", types: ["Plante", "Poison"] },
  { name: "Empiflor", types: ["Plante", "Poison"] },
  { name: "Tentacool", types: ["Eau", "Poison"] },
  { name: "Tentacruel", types: ["Eau", "Poison"] },
  { name: "Racaillou", types: ["Roche", "Sol"] },
  { name: "Gravalanch", types: ["Roche", "Sol"] },
  { name: "Grolem", types: ["Roche", "Sol"] },
  { name: "Ponyta", types: ["Feu"] },
  { name: "Galopa", types: ["Feu"] },
  { name: "Ramoloss", types: ["Eau", "Psy"] },
  { name: "Flagadoss", types: ["Eau", "Psy"] },
  { name: "Magnéti", types: ["Électrik", "Acier"] },
  { name: "Magnéton", types: ["Électrik", "Acier"] },
  { name: "Canarticho", types: ["Normal", "Vol"] },
  { name: "Doduo", types: ["Normal", "Vol"] },
  { name: "Dodrio", types: ["Normal", "Vol"] },
  { name: "Otaria", types: ["Eau"] },
  { name: "Lamantine", types: ["Eau", "Glace"] },
  { name: "Tadmorv", types: ["Poison"] },
  { name: "Grotadmorv", types: ["Poison"] },
  { name: "Kokiyas", types: ["Eau"] },
  { name: "Crustabri", types: ["Eau", "Glace"] },
  { name: "Fantominus", types: ["Spectre", "Poison"] },
  { name: "Spectrum", types: ["Spectre", "Poison"] },
  { name: "Ectoplasma", types: ["Spectre", "Poison"] },
  { name: "Onix", types: ["Roche", "Sol"] },
  { name: "Soporifik", types: ["Psy"] },
  { name: "Hypnomade", types: ["Psy"] },
  { name: "Krabby", types: ["Eau"] },
  { name: "Krabboss", types: ["Eau"] },
  { name: "Voltorbe", types: ["Électrik"] },
  { name: "Électrode", types: ["Électrik"] },
  { name: "Nœunœuf", types: ["Plante", "Psy"] },
  { name: "Noadkoko", types: ["Plante", "Psy"] },
  { name: "Osselait", types: ["Sol"] },
  { name: "Ossatueur", types: ["Sol"] },
  { name: "Kicklee", types: ["Combat"] },
  { name: "Tygnon", types: ["Combat"] },
  { name: "Excelangue", types: ["Normal"] },
  { name: "Smogo", types: ["Poison"] },
  { name: "Smogogo", types: ["Poison"] },
  { name: "Rhinocorne", types: ["Sol", "Roche"] },
  { name: "Rhinoféros", types: ["Sol", "Roche"] },
  { name: "Leveinard", types: ["Normal"] },
  { name: "Saquedeneu", types: ["Plante"] },
  { name: "Kangourex", types: ["Normal"] },
  { name: "Hypotrempe", types: ["Eau"] },
  { name: "Hypocéan", types: ["Eau"] },
  { name: "Poissirène", types: ["Eau"] },
  { name: "Poissoroy", types: ["Eau"] },
  { name: "Stari", types: ["Eau"] },
  { name: "Staross", types: ["Eau", "Psy"] },
  { name: "M. Mime", types: ["Psy", "Fée"] },
  { name: "Insécateur", types: ["Insecte", "Vol"] },
  { name: "Lippoutou", types: ["Glace", "Psy"] },
  { name: "Élektek", types: ["Électrik"] },
  { name: "Magmar", types: ["Feu"] },
  { name: "Scarabrute", types: ["Insecte"] },
  { name: "Tauros", types: ["Normal"] },
  { name: "Magicarpe", types: ["Eau"] },
  { name: "Léviator", types: ["Eau", "Vol"] },
  { name: "Lokhlass", types: ["Eau", "Glace"] },
  { name: "Métamorph", types: ["Normal"] },
  { name: "Évoli", types: ["Normal"] },
  { name: "Aquali", types: ["Eau"] },
  { name: "Voltali", types: ["Électrik"] },
  { name: "Pyroli", types: ["Feu"] },
  { name: "Porygon", types: ["Normal"] },
  { name: "Amonita", types: ["Roche", "Eau"] },
  { name: "Amonistar", types: ["Roche", "Eau"] },
  { name: "Kabuto", types: ["Roche", "Eau"] },
  { name: "Kabutops", types: ["Roche", "Eau"] },
  { name: "Ptéra", types: ["Roche", "Vol"] },
  { name: "Ronflex", types: ["Normal"] },
  { name: "Artikodin", types: ["Glace", "Vol"] },
  { name: "Électhor", types: ["Électrik", "Vol"] },
  { name: "Sulfura", types: ["Feu", "Vol"] },
  { name: "Minidraco", types: ["Dragon"] },
  { name: "Draco", types: ["Dragon"] },
  { name: "Dracolosse", types: ["Dragon", "Vol"] },
  { name: "Mewtwo", types: ["Psy"] },
  { name: "Mew", types: ["Psy"] }
];

for (const { name, types } of pokemonTypes) {
    const pokemon = await Pokemon.findOne({ where: { name } });
    if (!pokemon) {
      console.warn(`Pokémon not found: ${name}`);
      continue;
    }
  
    const typeInstances = await Type.findAll({
      where: { name: types }
    });
  
    await pokemon.addTypes(typeInstances);
  }